version: '3.8'

services:
  php:
    container_name: php-php
    image: nvkmv/php-php
    restart: unless-stopped  
    networks:
      - otus_net

  nginx:
    container_name: nginx-php
    image: nvkmv/nginx-php
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - php 
        #volumes:
        #- ./nginx/src/nginx.conf:/etc/nginx/conf.d/nginx.conf    
    networks:
      - otus_net  

networks:
  otus_net:
    name: otus_net
    driver: bridge
